name: Label PR

on:
  workflow_call:
    secrets:
      BOT_TOKEN:
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  autolabel:
    runs-on: ubuntu-latest
    name: Automatically Label PR
    if: ${{ !github.event.pull_request.draft && !contains(github.event.pull_request.labels.*.name , 'release') }}
    steps:
      - uses: actions/github-script@v7.0.0
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const labelPatterns = {
              feature: ["feature/*", "feat/*"],
              fix: "fix/*",
              chore: "chore/*",
              docs: "docs/*",
              refactor: "refactor/*",
              ci: "ci/*"
            };

            const branchName = context.payload.pull_request.head.ref
            const labelsToAdd = [];

            for (const label in labelPatterns) {
              const patterns = Array.isArray(labelPatterns[label]) ? labelPatterns[label] : [labelPatterns[label]];
              for (const pattern of patterns) {
                if (branchName.match(new RegExp(`^${pattern.replace('*', '.*')}$`))) {
                  labelsToAdd.push(label);
                  break;
                }
              }
            }

            if (labelsToAdd.length > 0) {
              core.info(`ℹ️ Matched the following labels: ${labelsToAdd.join(", ")}`)

              github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.payload.pull_request.number,
                labels: labelsToAdd
              })
            } else {
              core.info(`ℹ️ The HEAD ref of this PR does not match any of the specified patterns.`)
            }