on:
  push:
    tags:
      - "v*-rc*"
      - "v*-alpha*"
      - "v*-beta*"

name: Create pre-release
run-name: Create pre-release for `${{ github.ref_name }}`

jobs:
  release-wasm:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Build WASM module
        uses: Navigraph/cargo-msfs@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          run: npm run build:wasm-workflow

      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          files: 
            - ./interface-2020.zip
            - ./interface-2024.zip
          prerelease: true
          generate_release_notes: true

  # Enable in future to automate publishing of NPM package
  # release-js:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "18"
  #         registry-url: 'https://registry.npmjs.org'
  #         cache: "npm"

  #     - name: Install node modules
  #       run: npm ci

  #     - name: Build JS Interface
  #       run: cd src/js && npm run build

  #     - name: Publish to NPM
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: cd src/js && npm publish --tag next