on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo NAVDATA_SIGNED_URL=${{ secrets.NAVDATA_SIGNED_URL }} >> .env
      - name: Build WASM module
        run: npm run build:wasm-workflow
      - name: Test
        run: npm run test-workflow
      - name: Upload WASM module to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: msfs_navdata_interface.wasm
          path: ./out/msfs_navdata_interface.wasm
